'use client';

import { Download, FileText } from 'lucide-react';

interface ExportPortfolioProps {
  calculations: any[];
  investment: number;
  timeframe: number;
  riskTolerance: string;
}

export default function ExportPortfolio({ calculations, investment, timeframe, riskTolerance }: ExportPortfolioProps) {
  const exportToCSV = () => {
    if (!calculations.length) return;

    const headers = [
      'Protocol',
      'APY (%)',
      'Risk Level',
      'Category',
      'TVL',
      'Future Value ($)',
      'Total Earnings ($)',
      'ROI (%)',
      'Monthly Earnings ($)'
    ];

    const csvData = calculations.map(calc => [
      calc.name,
      calc.apy,
      calc.risk,
      calc.category,
      calc.tvl,
      calc.futureValue.toFixed(2),
      calc.totalEarnings.toFixed(2),
      calc.roi.toFixed(2),
      calc.monthlyEarnings.toFixed(2)
    ]);

    const csvContent = [
      headers.join(','),
      ...csvData.map(row => row.join(','))
    ].join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `defi-portfolio-${new Date().toISOString().split('T')[0]}.csv`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  };

  const exportSummary = () => {
    const totalFutureValue = calculations.reduce((sum, calc) => sum + (calc?.futureValue || 0), 0);
    const totalEarnings = calculations.reduce((sum, calc) => sum + (calc?.totalEarnings || 0), 0);
    const averageAPY = calculations.reduce((sum, calc) => sum + (calc?.apy || 0), 0) / calculations.length;

    const summary = `
DeFi Portfolio Summary Report
Generated: ${new Date().toLocaleDateString()}

INVESTMENT PARAMETERS:
- Initial Investment: $${investment.toLocaleString()}
- Timeframe: ${timeframe} months
- Risk Tolerance: ${riskTolerance}

PORTFOLIO PERFORMANCE:
- Total Future Value: $${totalFutureValue.toLocaleString()}
- Total Earnings: $${totalEarnings.toLocaleString()}
- Average APY: ${averageAPY.toFixed(2)}%
- Overall ROI: ${((totalEarnings / investment) * 100).toFixed(2)}%

PROTOCOL BREAKDOWN:
${calculations.map(calc => 
  `- ${calc.name}: ${calc.apy}% APY, ${calc.risk} risk, $${calc.futureValue.toLocaleString()} future value`
).join('\n')}

RISK ASSESSMENT:
- Conservative protocols: ${calculations.filter(c => c.risk === 'low').length}
- Medium risk protocols: ${calculations.filter(c => c.risk === 'medium').length}
- High risk protocols: ${calculations.filter(c => c.risk === 'high').length}

This report was generated by the DeFi Yield Calculator - a professional portfolio analysis tool.
    `.trim();

    const blob = new Blob([summary], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `defi-portfolio-summary-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-white/5 backdrop-blur-sm rounded-xl p-6 border border-white/10">
      <h3 className="text-lg font-semibold text-white mb-6">Export Portfolio Data</h3>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <button
          onClick={exportToCSV}
          disabled={!calculations.length}
          className="flex items-center justify-center space-x-2 px-4 py-3 bg-blue-600 hover:bg-blue-700 disabled:bg-gray-600 disabled:cursor-not-allowed rounded-lg text-white font-medium transition-colors"
        >
          <Download className="w-5 h-5" />
          <span>Export to CSV</span>
        </button>
        
        <button
          onClick={exportSummary}
          disabled={!calculations.length}
          className="flex items-center justify-center space-x-2 px-4 py-3 bg-green-600 hover:bg-green-700 disabled:bg-gray-600 disabled:cursor-not-allowed rounded-lg text-white font-medium transition-colors"
        >
          <FileText className="w-5 h-5" />
          <span>Export Summary</span>
        </button>
      </div>
      
      <div className="mt-4 text-sm text-gray-400">
        <p>• CSV export includes detailed protocol data for analysis</p>
        <p>• Summary export provides a comprehensive portfolio overview</p>
        <p>• Perfect for sharing with financial advisors or for record keeping</p>
      </div>
    </div>
  );
}
